### ISSUE TITLE
should set self.token_entity['datetime'] in refresh_token()

### ISSUE THREAD

**Issue by mattjcline** [itzmestar/Octoparse#1]
I believe this to be a bug. 
Steps to reproduce on master branch from `Octoparse/octoparse/`:

```
 $ python
Python 3.8.5 (default, Jul 21 2020, 10:42:08)
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import octoparse
>>> octo = octoparse.Octoparse()
Enter Octoparse Username: [USERNAME]
Password: [PASSWORD]
>>> octo.list_all_task_groups()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mcline/dev/octoparse-orig/octoparse/octoparse.py", line 241, in list_all_task_groups
    response = _get_request(self._get_url(path), self._get_access_token())
  File "/Users/mcline/dev/octoparse-orig/octoparse/octoparse.py", line 124, in _get_access_token
    timedelta = datetime.now() - self.token_entity['datetime']
KeyError: 'datetime'
```

I believe a fix would be to this line should be added to the refresh_token() method: 
https://github.com/itzmestar/Octoparse/commit/fea6a7ed866aedd74f45d1fc8144445a14cc8110#diff-52e2adcfc102844f5c18a891b46001dff96ea89b3a767ce60083de88aa69bc31R134

**Comment by itzmestar** [comment]
fixed in the new version 1.2.1
