### ISSUE TITLE
 unexpected keyword argument 'params'

### ISSUE THREAD

**Issue by itzmestar** [itzmestar/Octoparse#3]
Error encountered while running update_data_status():

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\py_game\venv38\lib\site-packages\octoparse\octoparse.py", line 305, in update_data_status
    response = _post_request(self._get_url(path), self._get_access_token(), params=params)
TypeError: _post_request() got an unexpected keyword argument 'params'

**Comment by itzmestar** [comment]
fixed in current version
